catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import home, contacts, detail_product, add_product, home_1, home_2

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('1/', home_1, name='home_1'),
    path('contacts/', contacts, name='contacts'),
    path('detail/<int:pk>/', detail_product, name='detail_product'),
    path('add_product/', add_product, name='add_product'),
    path('2/', home_2, name='home_2'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название категории",
        help_text="Введите название категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        **NULLABLE
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название продукта",
        help_text="Введите название продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        **NULLABLE
    )
    photo = models.ImageField(
        upload_to="products/",
        verbose_name="Фото продукта",
        help_text="Загрузите фото продукта",
        **NULLABLE
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите название категории",
        related_name="Products",
        **NULLABLE
    )
    price = models.IntegerField(
        verbose_name="Цена продукта",
        help_text="Введите цену продукта",
        **NULLABLE
    )
    created_at = models.DateField(
        verbose_name="Дата создания",
        help_text="Укажите дату создания",
        **NULLABLE
    )
    updated_at = models.DateField(
        verbose_name="Дата изменения",
        help_text="Укажите дату изменения",
        **NULLABLE
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = [
            "category", "name", "price",
            "created_at", "updated_at"
        ]


class Contact(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название контакта",
        help_text="Введите название контакта",
    )
    phone = models.CharField(
        max_length=20,
        verbose_name="Номер контакта",
        help_text="Введите номер контакта",
    )
    message = models.TextField(
        verbose_name="Сообщение",
        help_text="Введите сообщение",
        **NULLABLE
    )

    def __str__(self):
        return f"{self.name} {self.phone}"

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"
        ordering = [
            "name", "phone"
        ]

catalog/views.py
from django.shortcuts import render, get_object_or_404

from catalog.models import Product, Contact, Category


def home(request):
    context = {
        "title": 'Главная страница'
    }
    return render(request, "catalog/home.html", context)


def contacts(request):
    contact_list = Contact.objects.all()
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")

        Contact.objects.create(name=name, phone=phone, message=message)

        print(f"\n\nИмя - {name}\n" f"Телефон - {phone}\n" f"Сообщение - {message}\n\n")

    context = {
        'object_list': contact_list[len(contact_list) - 3 :],
        "title": 'Контакты'
    }

    return render(request, "catalog/catalog.html", context)


def detail_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'object': product,
        'title': product.name
    }
    return render(request, "catalog/detail_product.html", context)


def add_product(request):
    category_list = Category.objects.all()
    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")
        photo = request.FILES.get("photo")
        category_id = request.POST.get("category")
        category = Category.objects.get(id=category_id)
        price = request.POST.get("price")
        created_at = request.POST.get("created_at")
        updated_at = request.POST.get("updated_at")

        Product.objects.create(
            name=name,
            description=description,
            photo=photo,
            category=category,
            price=price,
            created_at=created_at,
            updated_at=updated_at
        )

    context = {
        'object_list': category_list,
        'title': 'Добавить продукт'
    }
    return render(request, 'catalog/add_product.html', context)


def home_1(request):
    product_list = Product.objects.all()
    latest_five_products = product_list[:4]
    context = {
        "object_list": latest_five_products,
        "title": 'Каталог'
    }
    print(latest_five_products)
    return render(request, "catalog/home_2.html", context)


def home_2(request):
    product_list = Product.objects.all()
    latest_five_products = product_list[4:]
    context = {
        "object_list": latest_five_products,
        "title": 'Каталог'
    }
    print(latest_five_products)
    return render(request, "catalog/home_2.html", context)

catalog/templates/catalog/add_product.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Добавить новый продукт</h1>
</div>

<div class="container">
    <div class="col-6 mx-auto">
        <div class="card text-center">
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="text" name="name" class="form-control" id="name"
                               placeholder="Введите название продукта">
                    </div>
                    <div class="mb-3">
                        <textarea name="description" class="form-control" id="description"
                                  placeholder="Введите описание продукта"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="formFile" class="form-label">Фото</label>
                        <input class="form-control" type="file" id="formFile" name="photo">
                    </div>
                    <div class="mb-3">
                          <select class="form-select" name="category" aria-label="Пример выбора по умолчанию">
                            <option selected>Выберите категорию</option>
                              {% for category in object_list %}
                              <option value="{{ category.id }}">{{ category.name }}</option>
                              {% endfor %}
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text">₽</span>
                        <input type="text" name="price" class="form-control" id="price"
                               placeholder="Введите цену продукта" aria-label="Amount (to the nearest ruble)">
                        <span class="input-group-text">.00</span>
                    </div>
                    <div class="mb-3">
                        <input type="text" name="created_at" class="form-control" id="created_at"
                               placeholder="Введите дату создания">
                    </div>
                    <div class="mb-3">
                        <input type="text" name="updated_at" class="form-control" id="updated_at"
                               placeholder="Введите дату изменения">
                    </div>
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}
{% block content %}
{% endblock %}

<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2024 - {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/catalog.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            {% for object in object_list %}
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Имя</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Телефон</td>
                            <td>{{ object.phone }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Сообщение</td>
                            <td>{{ object.message }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/detail_product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
    <p class="lead">Каталог - магазин по продажи электротехники</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <img src="{{ object.photo|media_filter }}" class="img-fluid" alt="...">
                    <h4 class="card-title">{{ object.name }}</h4>
                    <p class="card-text">Описание: {{ object.description }}
                    </p>
                    <p class="card-text"> Категория: {{ object.category }}
                    </p>
                    <p class="card-text"> Цена: {{ object.price }}
                    </p>
                    <p class="card-text"> Дата создания: {{ object.created_at }}
                    </p>
                    <p class="card-text"> Дата изменения: {{ object.updated_at }}
                    </p>
                    <a href="{% url 'catalog:home_1' %}" class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
    <p class="lead">Каталог - магазин по продажи электротехники</p>
</div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3 mt-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ object }}</h4>
                    <p class="card-text">
                        {{ object.description|slice:100 }}
                    </p>
                    <a href="{% url 'catalog:detail_product' object.pk %}" class="btn btn-primary">Посмотреть</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home_1.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
    <p class="lead">Каталог - магазин по продажи электротехники</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3 mt-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ object }}</h4>
                    <p class="card-text">
                        {{ object.description|slice:100 }}
                    </p>
                    <a href="{% url 'catalog:detail_product' object.pk %}" class="btn btn-primary">Посмотреть</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mt-5">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">«</span>
                        <span class="sr-only">Предыдущая</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="{% url 'catalog:home' %}">1</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'catalog:home_2' %}">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">»</span>
                        <span class="sr-only">Следующая</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home_2.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
    <p class="lead">Каталог - магазин по продажи электротехники</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3 mt-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ object }}</h4>
                    <p class="card-text">
                        {{ object.description|slice:100 }}
                    </p>
                    <a href="{% url 'catalog:detail_product' object.pk %}" class="btn btn-primary">Посмотреть</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="container">
        <div class="row text-center">
            <div class="mb-3 mt-5">
                <div class="btn-toolbar mb-3" role="toolbar" aria-label="Панель инструментов с группами кнопок">
                    <div class="btn-group me-2" role="group" aria-label="Первая группа">
                        <a type="button" class="btn btn-outline-secondary" href="{% url 'catalog:home' %}">1</a>
                        <a type="button" class="btn btn-outline-secondary" href="{% url 'catalog:home_2' %}">2</a>
                    </div>
                    <div class="mb-2 mt-2">
                        <label class="form-label">Страница</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Каталог</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home_1' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:add_product' %}">Добавить продукт</a>
    </nav>
</div>